[group:app]
programs=app-8001,app-8002,app-8003,app-8004

[program:app-8001]
command=python app.py --port=8001
directory=/opt/web/app/
user=www
autostart=false
autorestart=true
startsecs=5
redirect_stderr=true
stdout_logfile=/var/log/app@8001.log
loglevel=info
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20

[program:app-8002]
command=python app.py --port=8002
directory=/opt/web/app/
user=www
autostart=false
autorestart=true
startsecs=5
redirect_stderr=true
stdout_logfile=/var/log/app@8002.log
loglevel=info
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20

[program:app-8003]
command=python app.py --port=8003
directory=/opt/web/app/
user=www
autostart=false
autorestart=true
startsecs=5
redirect_stderr=true
stdout_logfile=/var/log/app@8003.log
loglevel=info
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20

[program:app-8004]
command=python app.py --port=8004
directory=/opt/web/app/
user=www
autostart=false  ; 在 supervisord 启动的时候也自动启动
autorestart=true
startsecs=5  ; 启动 5 秒后没有异常退出, 就当作已经正常启动了
redirect_stderr=true  ;把 stderr 重定向到 stdout
stdout_logfile=/var/log/app@8004.log
loglevel=info
stdout_logfile_maxbytes=50MB  ;stdout 日志文件大小
stdout_logfile_backups=20  ;stdout 日志文件备份数
